/*
insert license info here
*/
using System;
using System.Collections;
using System.Runtime.Serialization;

namespace Schedule.Data
{
	/// <summary>
	///	Generated by MyGeneration using the NHibernate Object Mapping template
	/// </summary>
	[DataContract]
	public  class Teacher
	{

		#region Private Members
		private bool m_isChanged;

		private string m_teacherno; 
		private string m_name; 
		private string m_pwd; 
		private string m_phone; 
		private string m_email; 
		private string m_address; 		
		#endregion

		#region Default ( Empty ) Class Constuctor
		/// <summary>
		/// default constructor
		/// </summary>
		public Teacher()
		{
			m_teacherno = String.Empty; 
			m_name = String.Empty; 
			m_pwd = String.Empty; 
			m_phone = String.Empty; 
			m_email = String.Empty; 
			m_address = String.Empty; 
		}
		#endregion // End of Default ( Empty ) Class Constuctor

		
		#region Public Properties
			
		/// <summary>
		/// 
		/// </summary>
		///
		[DataMember]
		public virtual string TeacherNo
		{
			get { return m_teacherno; }

			set	
			{	
				if( value == null )
					throw new ArgumentOutOfRangeException("Null value not allowed for TeacherNo", value, "null");
				
				if(  value.Length > 200)
					throw new ArgumentOutOfRangeException("Invalid value for TeacherNo", value, value.ToString());
				
				if(m_teacherno != value)
				{
					m_teacherno = value;
					m_isChanged = true;
					//OnPropertyChanged("TeacherNo");
					
				}
			}
		}
			
		/// <summary>
		/// 
		/// </summary>
		///
		[DataMember]
		public virtual string Name
		{
			get { return m_name; }

			set	
			{	
				if(  value != null &&  value.Length > 200)
					throw new ArgumentOutOfRangeException("Invalid value for Name", value, value.ToString());
				
				if(m_name != value)
				{
					m_name = value;
					m_isChanged = true;
					//OnPropertyChanged("Name");
					
				}
			}
		}
			
		/// <summary>
		/// 
		/// </summary>
		///
		[DataMember]
		public virtual string Pwd
		{
			get { return m_pwd; }

			set	
			{	
				if(  value != null &&  value.Length > 200)
					throw new ArgumentOutOfRangeException("Invalid value for Pwd", value, value.ToString());
				
				if(m_pwd != value)
				{
					m_pwd = value;
					m_isChanged = true;
					//OnPropertyChanged("Pwd");
					
				}
			}
		}
			
		/// <summary>
		/// 
		/// </summary>
		///
		[DataMember]
		public virtual string Phone
		{
			get { return m_phone; }

			set	
			{	
				if(  value != null &&  value.Length > 200)
					throw new ArgumentOutOfRangeException("Invalid value for Phone", value, value.ToString());
				
				if(m_phone != value)
				{
					m_phone = value;
					m_isChanged = true;
					//OnPropertyChanged("Phone");
					
				}
			}
		}
			
		/// <summary>
		/// 
		/// </summary>
		///
		[DataMember]
		public virtual string Email
		{
			get { return m_email; }

			set	
			{	
				if(  value != null &&  value.Length > 200)
					throw new ArgumentOutOfRangeException("Invalid value for Email", value, value.ToString());
				
				if(m_email != value)
				{
					m_email = value;
					m_isChanged = true;
					//OnPropertyChanged("Email");
					
				}
			}
		}
			
		/// <summary>
		/// 
		/// </summary>
		///
		[DataMember]
		public virtual string Address
		{
			get { return m_address; }

			set	
			{	
				if(  value != null &&  value.Length > 200)
					throw new ArgumentOutOfRangeException("Invalid value for Address", value, value.ToString());
				
				if(m_address != value)
				{
					m_address = value;
					m_isChanged = true;
					//OnPropertyChanged("Address");
					
				}
			}
		}
			
		/// <summary>
		/// Returns whether or not the object has changed it's values.
		/// </summary>
		public bool IsChanged
		{
			get { return m_isChanged; }
		}
				
		#endregion 

		#region Equals And HashCode Overrides
		/// <summary>
		/// local implementation of Equals based on unique value members
		/// </summary>
		public override bool Equals( object obj )
		{
			if( this == obj ) return true;
			if( ( obj == null ) || ( obj.GetType() != this.GetType() ) ) return false;
			Teacher castObj = (Teacher)obj; 
			return ( castObj != null ) &&
				( this.m_teacherno == castObj.TeacherNo );
		}
		
		/// <summary>
		/// local implementation of GetHashCode based on unique value members
		/// </summary>
		public override int GetHashCode()
		{
			
			int hash = 57; 
			hash = 27 * hash * m_teacherno.GetHashCode();
			return hash; 
		}
		#endregion
			}
}
